# Site settings
title: "The Black Watch"
author: "From Many, One."
description: "We keep an eye on the things no one else wants to see."
keywords: "Metaphysics, physics, occultism, mystery"
biography: "Born from that which recedes to One."

baseurl: ""
url: "http://hugosereno.eu"



simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/

theme: papyrus
